// A curated list of popular Google Fonts, used to populate the editor's font
// picker. Just family names — fonts are loaded on demand via `font-loader.ts`,
// so this stays a plain data module (no API key, no network at build time).

export const GOOGLE_FONTS: string[] = [
  "Inter",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Poppins",
  "Source Sans 3",
  "Raleway",
  "Nunito",
  "Nunito Sans",
  "Work Sans",
  "Rubik",
  "Noto Sans",
  "Ubuntu",
  "Mulish",
  "Inter Tight",
  "DM Sans",
  "Manrope",
  "Plus Jakarta Sans",
  "Figtree",
  "Onest",
  "Outfit",
  "Sora",
  "Space Grotesk",
  "Epilogue",
  "Lexend",
  "Karla",
  "Quicksand",
  "Josefin Sans",
  "Cabin",
  "Barlow",
  "Barlow Condensed",
  "Oswald",
  "Anton",
  "Bebas Neue",
  "Archivo",
  "Archivo Black",
  "Kanit",
  "Teko",
  "Fjalla One",
  "PT Sans",
  "PT Serif",
  "Merriweather",
  "Playfair Display",
  "Lora",
  "Libre Baskerville",
  "Bitter",
  "Crimson Text",
  "EB Garamond",
  "Cormorant Garamond",
  "Source Serif 4",
  "Noto Serif",
  "Spectral",
  "Zilla Slab",
  "Domine",
  "Frank Ruhl Libre",
  "Roboto Slab",
  "Arvo",
  "Slabo 27px",
  "DM Serif Display",
  "Fraunces",
  "Newsreader",
  "Bodoni Moda",
  "Instrument Serif",
  "Roboto Mono",
  "Space Mono",
  "JetBrains Mono",
  "IBM Plex Mono",
  "IBM Plex Sans",
  "IBM Plex Serif",
  "Fira Code",
  "Source Code Pro",
  "Inconsolata",
  "Dancing Script",
  "Pacifico",
  "Caveat",
  "Sacramento",
  "Satisfy",
  "Great Vibes",
  "Lobster",
  "Comfortaa",
  "Righteous",
  "Permanent Marker",
  "Shadows Into Light",
  "Indie Flower",
  "Amatic SC",
  "Abril Fatface",
  "Alfa Slab One",
  "Titan One",
  "Chewy",
  "Baloo 2",
  "Fredoka",
  "Concert One",
  "Patua One",
  "Cinzel",
  "Marcellus",
  "Cardo",
  "Prata",
  "Tinos",
  "Signika",
  "Hind",
  "Assistant",
  "Heebo",
  "Overpass",
  "Red Hat Display",
  "Albert Sans",
  "Schibsted Grotesk",
  "Bricolage Grotesque",
];
